In [4]:
import pandas as pd

In [5]:
df_time_series = pd.read_csv(".\AirPassengers.csv")
df_time_series.head()

     Month  #Passengers
0  1949-01          112
1  1949-02          118
2  1949-03          132
3  1949-04          129
4  1949-05          121

In [6]:
df_time_series["step"] = range(len(df_time_series))
df_time_series.head()

     Month  #Passengers  step
0  1949-01          112     0
1  1949-02          118     1
2  1949-03          132     2
3  1949-04          129     3
4  1949-05          121     4

In [7]:
df_time_series["cum_sum"] = df_time_series["#Passengers"].cumsum()
df_time_series["cum_max"] = df_time_series["#Passengers"].cummax()
df_time_series["cum_min"] = df_time_series["#Passengers"].cummin()
df_time_series.head()

     Month  #Passengers  step  cum_sum  cum_max  cum_min
0  1949-01          112     0      112      112      112
1  1949-02          118     1      230      118      112
2  1949-03          132     2      362      132      112
3  1949-04          129     3      491      132      112
4  1949-05          121     4      612      132      112

In [8]:
import numpy as np
temp_date = df_time_series["Month"].map(lambda x : x.split("-"))

In [9]:
temp_date = np.array(temp_date.values.tolist())
temp_date[:5]

array([['1949', '01'],
       ['1949', '02'],
       ['1949', '03'],
       ['1949', '04'],
       ['1949', '05']], dtype='|S4')

In [10]:
df_time_series["year"] = temp_date[:, 0]
df_time_series["month"] = temp_date[:, 1]

In [11]:
df_time_series.head()

     Month  #Passengers  step  cum_sum  cum_max  cum_min  year month
0  1949-01          112     0      112      112      112  1949    01
1  1949-02          118     1      230      118      112  1949    02
2  1949-03          132     2      362      132      112  1949    03
3  1949-04          129     3      491      132      112  1949    04
4  1949-05          121     4      612      132      112  1949    05

In [12]:
df_time_series["diff"] = df_time_series["#Passengers"].diff().fillna(0)
df_time_series[:5]

     Month  #Passengers  step  cum_sum  cum_max  cum_min  year month  diff
0  1949-01          112     0      112      112      112  1949    01   0.0
1  1949-02          118     1      230      118      112  1949    02   6.0
2  1949-03          132     2      362      132      112  1949    03  14.0
3  1949-04          129     3      491      132      112  1949    04  -3.0
4  1949-05          121     4      612      132      112  1949    05  -8.0

In [13]:
df_time_series["#Passengers"].pct_change().map(lambda x : x*100).map(lambda x : " %.2f" % x)

0          nan
1         5.36
2        11.86
3        -2.27
4        -6.20
5        11.57
6         9.63
7         0.00
8        -8.11
9       -12.50
10      -12.61
11       13.46
12       -2.54
13        9.57
14       11.90
15       -4.26
16       -7.41
17       19.20
18       14.09
19        0.00
20       -7.06
21      -15.82
22      -14.29
23       22.81
24        3.57
25        3.45
26       18.67
27       -8.43
28        5.52
29        3.49
        ...
114      12.87
115       2.85
116     -20.00
117     -11.14
118     -13.65
119       8.71
120       6.82
121      -5.00
122      18.71
123      -2.46
124       6.06
125      12.38
126      16.10
127       2.01
128     -17.17
129     -12.10
130     -11.06
131      11.88
132       2.96
133      -6.24
134       7.16
135      10.02
136       2.39
137      13.35
138      16.26
139      -2.57
140     -16.17
141      -9.25
142     -15.40
143      10.77
Name: #Passengers, Length: 144, dtype: object

In [26]:
df_time_series["pct"]= df_time_series["#Passengers"].pct_change().map(lambda x: "%.2f" % (x * 100))

In [31]:
patent = pd.read_csv(".\sea_managing_raw.csv",encoding="cp949")
patent.head()

,국가코드,DB종류,특허/실용 구분,문헌종류 코드,발명의 명칭,요약,대표청구항,청구항 수,NUMBER,출원일,...,Original CPC Main,Original CPC All,Original IPC Main,Original IPC All,Original US Class Main[US],Original US Class All[US],Original FI[JP],Original F-term[JP],Original Theme Code [JP],WIPS ON key
0,US,US,P,B2,Turboengine water wash system,A system for cleaning gas turbine engines is d...,1. An apparatus for cleaning wing mounted gas ...,64,11/644784,2006-12-22,...,NaN,NaN,B08B-009/00,B08B-009/00,134/166.R,134/166.R | 134/138,NaN,NaN,NaN,4.910000e+12
1,US,US,P,A1,TREATMENT OF TAILINGS WITH DEIONIZED SILICATE ...,A process for treating a tailings stream compr...,1. A process for treating a tailings stream co...,20,13/848244,2013-03-21,...,B09B-0003/0025,B09B-0003/0025,B09B-003/00,B09B-003/00,106/627,106/627 | 106/600 | 106/631 | 106/632 | 106/63...,NaN,NaN,NaN,5.410000e+12
2,US,US,P,A1,Method And Apparatus For Treating Tailings Usi...,There is a method described of treating tailin...,1. A method of treating tailings having a comb...,18,13/765924,2013-02-13,...,C02F-0001/48,C02F-0001/48,C02F-001/48,C02F-001/48,204/554,204/554,NaN,NaN,NaN,5.410000e+12
3,US,US,P,A1,METHOD FOR STABILIZING WASTE AND HAZARDOUS WASTE,The invention provides a process for stabilizi...,"1. A method for stabilizing hazardous waste, c...",20,13/767408,2013-02-14,...,A62D-0003/33,A62D-0003/33 | G21F-0009/302,A62D-003/33,A62D-003/33 | G21F-009/30,588/002,588/002 | 588/315,NaN,NaN,NaN,5.410000e+12
4,US,US,P,B2,Water treatment process and plant using ballas...,A method for treating wastewater using a balla...,1. A method of treating wastewater including: ...,18,12/521154,2007-12-26,...,NaN,NaN,C02F-001/52,C02F-001/52 | B01D-021/01 | B01D-021/02 | B01D...,210/709,210/709 | 210/711 | 210/712 | 210/713 | 210/71...,NaN,NaN,NaN,4.910000e+12

In [32]:
patent["NUMBER"].isnull().sum()

0

In [29]:
df_patent = patent[["NUMBER","Original US Class All[US]"]]

KeyError: "['\\xec\\xb6\\x9c\\xec\\x9b\\x90\\xeb\\xb2\\x88\\xed\\x98\\xb8'] not in index"

In [22]:
df_patent["Original US Class All[US]"][:5]

NameError: name 'df_patent' is not defined

In [23]:
df_patent["Original US Class All[US]"].map(lambda x : x.split("|")).tolist()

NameError: name 'df_patent' is not defined

In [32]:
edge_list = []
for data in zip(df_patent["출원번호"].tolist() ,df_patent["Original US Class All[US]"].map(lambda x : x.split("|")).tolist()):
    for value in data[1]:
        edge_list.append([data[0], value.strip()])

In [33]:
edge_list[:10]

[['11/644784', '134/166.R'],
 ['11/644784', '134/138'],
 ['13/848244', '106/627'],
 ['13/848244', '106/600'],
 ['13/848244', '106/631'],
 ['13/848244', '106/632'],
 ['13/848244', '106/634'],
 ['13/848244', '210/702'],
 ['13/765924', '204/554'],
 ['13/767408', '588/002']]

In [34]:
df_edge_list = pd.DataFrame(edge_list)

In [35]:
df_edge_list["rating"] = 1

In [36]:
df_edge_list.groupby([0,1])["rating"].sum().unstack().fillna(0)

1,004/114.1,004/144.1,004/222,004/459,004/679,009/008.P,014/023,014/024,014/028,014/073,...,800/295,800/320,901/001,901/002,901/027,901/031,977/742,977/840,977/932,D25/113
0,,,,,,,,,,,,,,,,,,,,,
05/583686,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
05/634273,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
05/636159,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
05/677447,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
05/701218,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
05/772460,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
05/801551,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
05/807560,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
05/809031,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
05/935641,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
05/935672,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
05/935673,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
06/014118,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
06/111812,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
06/153826,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
06/325778,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
06/364998,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
06/443529,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
06/466803,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
06/511329,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
06/556004,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
06/578352,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
06/587591,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
06/591701,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
06/607313,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
06/663271,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
06/705226,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
06/740506,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
06/781869,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
06/850862,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13/761140,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13/765924,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13/767408,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13/776329,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13/784342,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13/801483,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13/810839,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13/811380,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13/813754,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13/814126,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13/817594,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13/836061,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13/848244,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13/863745,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13/886135,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13/915506,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13/922755,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13/939857,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13/939901,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13/944223,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13/952172,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13/955538,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13/955978,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13/969592,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13/976462,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13/981662,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13/983259,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13/992113,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13/994340,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14/035312,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0